In [1]:
import numpy as np
import pandas as pd
import altair as alt

A matrix is an ordered **collection of vectors**. we say that a matrix _A_ has _m_ rows and _n_ columns, and each entry of _A_ is defined as $a_{ij} = 1,...,m$ and $j=1,...,n$  
In NumPy, we contruct matrices with the array method

In [2]:
A = np.array([[0,2],
             [1,4]])

print(A)

[[0 2]
 [1 4]]


### Basic Matrix operations

#### Matrix-matrix addition
matrices are added in an element-wise fashion, where each cell of _A_ is added to its corresponding cell of _B_

In [4]:
A = np.array([[0,2],
             [2,4],
             [8,9]])

B = np.array([[4,5],
             [10, 90],
             [0,0]])

result = np.add(A,B)
#the same result is given by A+B
print(result)

[[ 4  7]
 [12 94]
 [ 8  9]]


#### Matrix-scalar multiplication
Matrix-scalar multiplication is an element-wise operation, where each element of _A_ is multiplied by a scalr $\alpha$

In [5]:
alpha = 2
A = np.array([[1,2],
             [3,4]])
result = np.multiply(alpha, A)
#the same result is given by A*alpha

print(result)

[[2 4]
 [6 8]]
